linux-setup-steps: &linux-setup-steps
  dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
  os: linux
  language: python
  install:
    - pip install --upgrade pip pipenv
    - pipenv install --dev
    - sudo apt-get install ninja-build

windows-setup-steps: &windows-setup-steps
  os: windows
  language: cpp  # 'language: python' is not yet supported on Windows
  before_install: choco install python3
  install:
    - py -m pip install --upgrade pip pipenv
    - py -m pipenv install --dev

osx-setup-steps: &osx-setup-steps
  os: osx
  language: shell  # 'language: python' is not yet supported on macOS
  before_install: brew upgrade python
  install:
    - brew install ninja
    - pip install --upgrade pip pipenv
    - pipenv install --dev
    - pipenv install PyObjC  # This is not in the Pipfile because it breaks other platforms https://github.com/pypa/pipenv/issues/3187

matrix:
  include:
    - name: "Linux: test with make and ninja on Python 3.7"
      python: '3.7'
      <<: *linux-setup-steps
      script: pipenv run -v test -f make,ninja

    - name: "Linux: test with make and ninja on Python 2.7"
      python: '2.7'
      <<: *linux-setup-steps
      script: pipenv run -v test -f make,ninja

    - name: "Windows: test with mocks on Python 3.7"
      <<: *windows-setup-steps
      env:
        - GYP_MSVS_VERSION=2017
      script: py -m pipenv run -v test -f make-mock,msvs-mock

    - name: "macOS: test with make and ninja on Python 3.7"
      <<: *osx-setup-steps
      script: pipenv run -v test -f make,ninja

    - name: "lint with Python 2.7"
      python: '2.7'
      <<: *linux-setup-steps
      script: pipenv run -v lint

    - name: "lint with Python 3.7"
      python: '3.7'
      <<: *linux-setup-steps
      script: pipenv run -v lint

notifications:
  slack: node4good:C2EI9vo04FY8Ce5u7kcOLlDw
